/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dbb.struts.action;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.dbb.domain.Users;
import com.dbb.service.UserService;
import com.dbb.struts.form.UserForm;
import com.dbb.utils.MyTools;

/** 
 * MyEclipse Struts
 * Creation date: 05-27-2017
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="userForm" scope="request"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		
		//取出表单信息
		String name=userForm.getName();
		FormFile formFile=userForm.getMyphoto();
		
		//原本的文件名
		String filepath=formFile.getFileName();
		System.out.print(filepath);
		
		//新的文件名
		String filenewname=null;
		
		InputStream is=null;
		OutputStream os=null;
		try {
			//得到输入流
			is=formFile.getInputStream();
			
			//得到files文件夹在web服务器中的真实地址，即是文件保存的位置
			String keeppath=this.getServlet().getServletContext().getRealPath("/files");
			System.out.print(keeppath);
			
			filenewname=MyTools.getNewFileName(filepath);
			//通过保存文件的实际地址，来得到输出流
			os=new FileOutputStream(keeppath+"\\"+filenewname);
			
			//读取文件并写到服务器
			int len=0;
			byte []bytes=new byte[1024];
			
			//循环读取
			while((len=is.read(bytes))>0){
				
				//读一点，写一点
				os.write(bytes, 0, len);
			}
			
			//如果文件上传成功，就把用户的信息传到数据库中
			UserService userService=new UserService();
			Users user=new Users();
			user.setName(name);
			user.setFileName(filepath);
			user.setFileNewName(filenewname);
			
			if(!userService.addUser(user)){
				//添加错误
				return mapping.findForward("err");
				
			}
			
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}finally{
			try {
				os.close();
				is.close();
				
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
		
		return mapping.findForward("registerOk");
	}
}