/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dbb.struts.action;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dbb.service.UserService;

/** 
 * MyEclipse Struts
 * Creation date: 05-27-2017
 * 
 * XDoclet definition:
 * @struts.action
 */
public class UserListAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		//创建userservice对象，获取用户列表
		UserService userService=new UserService();
		ArrayList aList=userService.getUserList();
		
		request.setAttribute("userlist", aList);
		return mapping.findForward("showUsers");
	}
}